FirstTeamCore/Models/SelfFood.cs
using System;
using System.Collections.Generic;

namespace FirstTeamCore.Models
{
    public partial class SelfFood
    {
        public SelfFood()
        {
            SelfOrders = new HashSet<SelfOrder>();
        }

        public int 自選飲食編號id { get; set; }
        public string? 圖片 { get; set; }
        public int? 需求人數 { get; set; }
        public int? 需求份數 { get; set; }
        public string? 商品名稱 { get; set; }
        public string? 商品內容 { get; set; }
        public int? 單價 { get; set; }
        public string? 建立人 { get; set; }
        public DateTime? 建立時間 { get; set; }
        public string? 修改人 { get; set; }
        public DateTime? 修改時間 { get; set; }

        public virtual ICollection<SelfOrder> SelfOrders { get; set; }
    }
}

FirstTeamCore/Models/SelfOrder.cs
using System;
using System.Collections.Generic;

namespace FirstTeamCore.Models
{
    public partial class SelfOrder
    {
        public int 自選訂單編號id { get; set; }
        public int? 會員編號 { get; set; }
        public DateTime? 入住時間 { get; set; }
        public DateTime? 退住時間 { get; set; }
        public int? 露營天數 { get; set; }
        public int? 預計人數 { get; set; }
        public int? 營區細項編號 { get; set; }
        public int? 自選飲食 { get; set; }
        public int? 租賃商店 { get; set; }
        public int? 租借總價 { get; set; }
        public int? 自選訂單總價 { get; set; }
        public string? 評論 { get; set; }
        public int? 評分 { get; set; }
        public string? 建立人 { get; set; }
        public DateTime? 建立時間 { get; set; }
        public string? 修改人 { get; set; }
        public DateTime? 修改時間 { get; set; }

        public virtual MemberInfo? 會員編號Navigation { get; set; }
        public virtual CampDetail? 營區細項編號Navigation { get; set; }
        public virtual RentDetail? 租賃商店Navigation { get; set; }
        public virtual SelfFood? 自選飲食Navigation { get; set; }
    }
}

FirstTeamCore/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;

namespace FirstTeamCore.Controllers
{
    public class MemberController : Controller
    {
        public IActionResult Info()
        {
            return View();
        }

        public IActionResult Review()
        {
            return View();
        }
    }
}

FirstTeamCore/Controllers/SelfController.cs
using Microsoft.AspNetCore.Mvc;
using FirstTeamCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;
using FirstTeamCore.ViewModel;

namespace FirstTeamCore.Controllers
{
    public class SelfController : Controller
    {

        IWebHostEnvironment _environment; //全域變數_environment
        public SelfController(IWebHostEnvironment p)
        {
            _environment = p;
        }



        //<!-- ======= 自選飲食 ======= -->
        FTdbContext db = new FTdbContext();
        //查詢
        public IActionResult SelfFood(CKeywordViewModel vm)
        //public IActionResult SelfFood(string txtKeyword)
        {
          
            IEnumerable<SelfFood> datas = null;
            if (string.IsNullOrEmpty(vm.txtKeyword))
            {
                datas = from t in db.SelfFoods
                        select t;
            }
            else
            {
                datas = db.SelfFoods.Where(t => t.商品名稱.Contains(vm.txtKeyword)||
                t.商品內容.Contains(vm.txtKeyword));
            }               

            return View(datas);
        }
    
       
        public IActionResult FoodCreate()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FoodCreate(SelfFood p, IFormFile photo)
        {
            
            if (photo != null)
            {
                string photoName = Guid.NewGuid().ToString() + ".jpg";
                string path = _environment.WebRootPath + "/images/" + photoName;
                p.圖片 = photoName;
                photo.CopyTo(new FileStream(path, FileMode.Create));
            }
            else
            {
                p.圖片 = "empty.jpg";
            }
         
            db.SelfFoods.Add(p);
            db.SaveChanges();
            return RedirectToAction("SelfFood");
        }


        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                
                SelfFood delSelfFood = db.SelfFoods.FirstOrDefault(t => t.自選飲食編號id == id);
                if (delSelfFood != null)
                {
                    db.SelfFoods.Remove(delSelfFood);
                    db.SaveChangesAsync();
                }
            }
            return RedirectToAction("SelfFood");
        }


        //第一步找資料
        public IActionResult FoodEdit(int? id)
        {
            if (id != null)
            {
                
                SelfFood x = db.SelfFoods.FirstOrDefault(t => t.自選飲食編號id == id);
                if (x != null)
                    return View(x);

            }
            return RedirectToAction("SelfFood"); //刪除後回傳給List
        }
        [HttpPost]
        //存入資料庫
        public IActionResult FoodEdit(CSelfFoodViewModel p)  //使用CSelfFoodViewModel
        {
            
            SelfFood x = db.SelfFoods.FirstOrDefault(t => t.自選飲食編號id == p.自選飲食id);
            if (x != null)
            {
                if (p.photo != null)
                {
                    string photoName = Guid.NewGuid().ToString() + ".jpg";
                    string path = _environment.WebRootPath + "/images/" + photoName;
                    x.圖片 = photoName;
                    p.photo.CopyTo(new FileStream(path, FileMode.Create));
                }

                x.商品名稱 = p.商品名稱;
                x.商品內容 = p.商品內容;
                x.需求人數 = p.需求人數; 
                x.需求份數 = p.需求份數;
                x.單價 = p.單價;
                
                db.SaveChangesAsync();
            }
            return RedirectToAction("SelfFood");
        }


        //<!-- ======= End自選飲食 ======= -->



        //<!-- ======= 自選訂單 ======= -->

        public IActionResult SelfOrder()
        {
            return View();
        }


         

        //<!-- ======= 自選細項 ======= -->

        public IActionResult SelfDetail()
        {
            return View();
        }


     



    }
}

FirstTeamCore/Views/Self/FoodCreate.cshtml
@model FirstTeamCore.Models.SelfFood

@{
    ViewData["Title"] = "FoodCreate";
}

<h1>新增資料</h1>


<h4>自選飲食</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="FoodCreate" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label class="control-label">產品照片</label>
                <input type="file" class="form-control" name="photo" />
            </div>
            <div class="form-group">
                <label asp-for="需求人數" class="control-label"></label>
                <input asp-for="需求人數" class="form-control" />
                <span asp-validation-for="需求人數" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="需求份數" class="control-label"></label>
                <input asp-for="需求份數" class="form-control" />
                <span asp-validation-for="需求份數" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="商品名稱" class="control-label"></label>
                <input asp-for="商品名稱" class="form-control" />
                <span asp-validation-for="商品名稱" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="商品內容" class="control-label"></label>
                <input asp-for="商品內容" class="form-control" />
                <span asp-validation-for="商品內容" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="單價" class="control-label"></label>
                <input asp-for="單價" class="form-control" />
                <span asp-validation-for="單價" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="送出" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SelfFood">返回自選飲食主頁</a>
</div>


<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstTeamCore/Views/Self/FoodEdit.cshtml
@model FirstTeamCore.Models.SelfFood

@{
    ViewData["Title"] = "FoodEdit";
}



<h1>修改商品</h1>
<h4>自選飲食</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="FoodEdit" enctype="multipart/form-data">
            <!-- 加上enctype -->  
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" name="自選飲食編號id" value="@Model.自選飲食編號id" />

            <div class="form-group">
                <label class="control-label">產品照片</label>
                <input type="file" class="form-control" name="photo"/>
             
            </div>
            <div class="form-group">
                <label asp-for="需求人數" class="control-label"></label>
                <input asp-for="需求人數" class="form-control" />
                <span asp-validation-for="需求人數" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="需求份數" class="control-label"></label>
                <input asp-for="需求份數" class="form-control" />
                <span asp-validation-for="需求份數" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="商品名稱" class="control-label"></label>
                <input asp-for="商品名稱" class="form-control" />
                <span asp-validation-for="商品名稱" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="商品內容" class="control-label"></label>
                <input asp-for="商品內容" class="form-control" />
                <span asp-validation-for="商品內容" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="單價" class="control-label"></label>
                <input asp-for="單價" class="form-control" />
                <span asp-validation-for="單價" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SelfFood">返回自選飲食主頁</a>
</div>


<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstTeamCore/Views/Self/SelfDetail.cshtml
@{
    ViewData["Title"] = "SelfDetail";
}

<h1>SelfDetail</h1>
<html>

<body>
    <!-- 上方索引層 -->
    <div class="pagetitle">
        <h1>會員中心</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Member" asp-action="Info">Home</a></li>
                <li class="breadcrumb-item active">會員中心</li>
                <li class="breadcrumb-item active">會員資料總覽</li>
            </ol>
        </nav>
    </div>
    <!-- 索引層end -->

    <!-- ======= 主要表格 ======= -->
<section class="section dashboard">
    <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-12">
            <div class="row">


                <!-- Recent Sales -->
                <div class="col-12">
                    <div class="card recent-sales overflow-auto">

                        <div class="filter">
                            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                <li class="dropdown-header text-start">
                                    <h6>Filter</h6>
                                </li>

                                <li><a class="dropdown-item" href="#">Today</a></li>
                                <li><a class="dropdown-item" href="#">This Month</a></li>
                                <li><a class="dropdown-item" href="#">This Year</a></li>
                            </ul>
                        </div>

                        <div class="card-body">
                            <h5 class="card-title">Recent Sales <span>| Today</span></h5>

                            <table class="table table-borderless datatable">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Customer</th>
                                        <th scope="col">Product</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row"><a href="#">#2457</a></th>
                                        <td>Brandon Jacob</td>
                                        <td><a href="#" class="text-primary">At praesentium minu</a></td>
                                        <td>$64</td>
                                        <td><span class="badge bg-success">Approved</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row"><a href="#">#2147</a></th>
                                        <td>Bridie Kessler</td>
                                        <td><a href="#" class="text-primary">Blanditiis dolor omnis similique</a></td>
                                        <td>$47</td>
                                        <td><span class="badge bg-warning">Pending</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row"><a href="#">#2049</a></th>
                                        <td>Ashleigh Langosh</td>
                                        <td><a href="#" class="text-primary">At recusandae consectetur</a></td>
                                        <td>$147</td>
                                        <td><span class="badge bg-success">Approved</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row"><a href="#">#2644</a></th>
                                        <td>Angus Grady</td>
                                        <td><a href="#" class="text-primar">Ut voluptatem id earum et</a></td>
                                        <td>$67</td>
                                        <td><span class="badge bg-danger">Rejected</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row"><a href="#">#2644</a></th>
                                        <td>Raheem Lehner</td>
                                        <td><a href="#" class="text-primary">Sunt similique distinctio</a></td>
                                        <td>$165</td>
                                        <td><span class="badge bg-success">Approved</span></td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div><!-- End Recent Sales -->
            </div>
        </div><!-- End Left side columns -->

    </div>

</section>
    <!-- ======= End 主要表格 ======= -->

  

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

</body>

</html>

FirstTeamCore/Views/Self/SelfFood.cshtml
@model IEnumerable<FirstTeamCore.Models.SelfFood>

@{
    ViewData["Title"] = "SelfFood";
}



<h1>自選飲食</h1>

    <!-- 上方索引層 -->
    <div class="pagetitle">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">行程管理:自選</li>
                <li class="breadcrumb-item active">自選飲食</li>
            </ol>
        </nav>
    </div>
    <!-- 索引層end -->
    @using (Html.BeginForm())
    {
        <p>
            關鍵字
            @Html.TextBox("txtKeyword")
            <input type="submit" value="查詢" class="btn btn-secondary" />
        </p>
    }


    <p>
        <a asp-action="FoodCreate" class="btn btn-success">新增產品</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    序號
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.商品名稱)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.商品內容)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.圖片)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.單價)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.需求人數)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.需求份數)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>



            @{
                int count = 0;
                foreach (var item in Model)
                {

                    count++;

                    <tr>
                        <td>
                            @count
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.商品名稱)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.商品內容)
                        </td>
                        <td>
                            @*@Html.DisplayFor(modelItem => item.圖片)*@
                            <img src="~/images/@item.圖片" width="100" height="100" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.單價)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.需求人數)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.需求份數)
                        </td>
                        <td>
                            @Html.ActionLink("修改", "FoodEdit", new { id=item.自選飲食編號id }, new { @class="btn btn-success" })|
                            @Html.ActionLink("刪除", "Delete","Self", new {id=item.自選飲食編號id },new{onclick="return confirm('確定要刪除嗎?')",@class="btn btn-danger"})
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>



    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>






<!-- ======= 主要表格 ======= -->
@*<section class="section dashboard">
    <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-12">
            <div class="row">


                    <!-- Top Selling -->
                    <div class="col-12">
                        <div class="card top-selling overflow-auto">

                            <div class="filter">
                                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                    <li class="dropdown-header text-start">
                                        <h6>Filter</h6>
                                    </li>

                                    <li><a class="dropdown-item" href="#">Today</a></li>
                                    <li><a class="dropdown-item" href="#">This Month</a></li>
                                    <li><a class="dropdown-item" href="#">This Year</a></li>
                                </ul>
                            </div>

                            <div class="card-body pb-0">
                                <h5 class="card-title">Top Selling <span>| Today</span></h5>

                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">Preview</th>
                                            <th scope="col">Product</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Sold</th>
                                            <th scope="col">Revenue</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="assets/img/product-1.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Ut inventore ipsa voluptas nulla</a></td>
                                            <td>$64</td>
                                            <td class="fw-bold">124</td>
                                            <td>$5,828</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="assets/img/product-2.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Exercitationem similique doloremque</a></td>
                                            <td>$46</td>
                                            <td class="fw-bold">98</td>
                                            <td>$4,508</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="assets/img/product-3.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Doloribus nisi exercitationem</a></td>
                                            <td>$59</td>
                                            <td class="fw-bold">74</td>
                                            <td>$4,366</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="assets/img/product-4.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Officiis quaerat sint rerum error</a></td>
                                            <td>$32</td>
                                            <td class="fw-bold">63</td>
                                            <td>$2,016</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="assets/img/product-5.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Sit unde debitis delectus repellendus</a></td>
                                            <td>$79</td>
                                            <td class="fw-bold">41</td>
                                            <td>$3,239</td>
                                        </tr>
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div><!-- End Top Selling -->
            </div>
        </div><!-- End Left side columns -->

    </div>

</section>*@
<!-- ======= End 主要表格 ======= -->

FirstTeamCore/Views/Self/SelfOrder.cshtml
@{
    ViewData["Title"] = "SelfOrder";
}

<h1>SelfOrder</h1>

<html>

<body>
    <!-- 上方索引層 -->
    <div class="pagetitle">
        <h1>會員中心</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Member" asp-action="Info">Home</a></li>
                <li class="breadcrumb-item active">會員中心</li>
                <li class="breadcrumb-item active">會員資料總覽</li>
            </ol>
        </nav>
    </div>
    <!-- 索引層end -->
    <!-- ======= 主要表格 ======= -->
    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-12">
                <div class="row">


                    <!-- Top Selling -->
                    <div class="col-12">
                        <div class="card top-selling overflow-auto">

                            <div class="filter">
                                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                    <li class="dropdown-header text-start">
                                        <h6>Filter</h6>
                                    </li>

                                    <li><a class="dropdown-item" href="#">Today</a></li>
                                    <li><a class="dropdown-item" href="#">This Month</a></li>
                                    <li><a class="dropdown-item" href="#">This Year</a></li>
                                </ul>
                            </div>

                            <div class="card-body pb-0">
                                <h5 class="card-title">Top Selling <span>| Today</span></h5>

                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">Preview</th>
                                            <th scope="col">Product</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Sold</th>
                                            <th scope="col">Revenue</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="/assets/img/product-1.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Ut inventore ipsa voluptas nulla</a></td>
                                            <td>$64</td>
                                            <td class="fw-bold">124</td>
                                            <td>$5,828</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="/assets/img/product-2.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Exercitationem similique doloremque</a></td>
                                            <td>$46</td>
                                            <td class="fw-bold">98</td>
                                            <td>$4,508</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="/assets/img/product-3.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Doloribus nisi exercitationem</a></td>
                                            <td>$59</td>
                                            <td class="fw-bold">74</td>
                                            <td>$4,366</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="/assets/img/product-4.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Officiis quaerat sint rerum error</a></td>
                                            <td>$32</td>
                                            <td class="fw-bold">63</td>
                                            <td>$2,016</td>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="#"><img src="/assets/img/product-5.jpg" alt=""></a></th>
                                            <td><a href="#" class="text-primary fw-bold">Sit unde debitis delectus repellendus</a></td>
                                            <td>$79</td>
                                            <td class="fw-bold">41</td>
                                            <td>$3,239</td>
                                        </tr>
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div><!-- End Top Selling -->
                </div>
            </div><!-- End Left side columns -->

        </div>

    </section>
    <!-- ======= End 主要表格 ======= -->
   
</body>

</html>